#!/usr/bin/env bash

set -o pipefail

case "$1" in
    start )
        # Ignore SIGINT(Ctrl-C)
        trap '' 2

        aws ec2 describe-instances --filter "Name=instance-state-name,Values=running" \
            | jq -r '.Reservations[].Instances[] | {InstanceName: (.Tags[] | select(.Key=="Name").Value), InstanceId} | [.InstanceName, .InstanceId] | @tsv' \
            | fzf \
            | cut -f 2 \
            | xargs  -o aws ssm start-session --target
        ;;
    * )
        cat <<-EOF
usage: ssm-session <command>

command:
    start: Start session manager
EOF
        ;;
esac
